language: node_js

node_js:
    - '12'

script:
    - yarn test
    - yarn build

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: build
    on:
        tags: true
