language: node

before_script:
  - npm -g install yarn
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: hotfix
