name: Build and Deploy

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup nodejs
              uses: actions/setup-node@v2
              with:
                  node-version: '12'
            - name: Install dependencies and build
              run: |
                  yarn install
                  yarn build
            - name: Deploy to github pages
              if: startsWith(github.ref, 'ref/tags/')
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  branch: gh-pages
                  folder: build
